# Generated by Django 3.0.8 on 2020-08-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customerid', models.AutoField(primary_key=True, serialize=False)),
                ('PhoneNumber', models.PositiveIntegerField()),
                ('addres', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ordermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('pnonenumber', models.PositiveIntegerField()),
                ('address', models.TextField(max_length=50)),
                ('ordertime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('info', models.TextField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
