# Generated by Django 3.0.5 on 2020-08-24 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(db_index=True, max_length=256, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(db_index=True, max_length=256, unique=True)),
                ('info', models.TextField()),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('auth_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('publish_status', models.CharField(choices=[('d', 'draft'), ('p', 'publish')], default='d', max_length=1)),
                ('orderingid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('payment', models.CharField(choices=[('O', 'online'), ('C', 'Cash')], max_length=3)),
                ('coupon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pizaa.Coupon')),
                ('orderitems', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('publish_status', models.CharField(choices=[('d', 'draft'), ('p', 'publish')], default='d', max_length=1)),
                ('FoodId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, height_field='height_field', help_text='uplaod image', null=True, upload_to='post', width_field='width_field')),
                ('width_field', models.PositiveIntegerField(blank=True, default='1080', null=True)),
                ('height_field', models.PositiveIntegerField(blank=True, default='720', null=True)),
                ('price', models.PositiveIntegerField()),
                ('info', models.TextField()),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pizaa.Category')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-published_at'],
            },
        ),
    ]
