# Generated by Django 3.0.8 on 2020-08-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizaa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='ordereditems',
            field=models.CharField(default='pizza', max_length=10),
            preserve_default=False,
        ),
    ]
