# Generated by Django 3.0.8 on 2020-08-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizaa', '0002_ordermodel_ordereditems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='pnonenumber',
            new_name='phonenumber',
        ),
    ]
